name: my-action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "Hello this is the first step"
      - name: github checkout
        uses: actions/checkout@v6
